--tablas
CREATE TABLE "URBANATTBD"."USUARIOS"
  (
    "ID_USUARIO"                NUMBER NOT NULL ENABLE,
    "NOMBRE_USUARIO"            VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CONTRASENIA_USUARIO"       VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "FECHA_CREACION"            VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CANTIDAD_INTENTOS_INGRESO" NUMBER,
    "ESTADO"                    VARCHAR2(50 BYTE),
    "NOMBRE_COMPLETO"           VARCHAR2(200 BYTE),
    "ID_ROL_USUARIO"            NUMBER DEFAULT 1 NOT NULL ENABLE,
    "NOTA"                      VARCHAR2(200 BYTE),
    CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE,
    CONSTRAINT "USUARIOS_ROLES_FK1" FOREIGN KEY ("ID_ROL_USUARIO") REFERENCES "URBANATTBD"."ROLES" ("ID_ROL") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;

CREATE TABLE "URBANATTBD"."ROLES"
  (
    "ID_ROL" NUMBER NOT NULL ENABLE,
    "NOMBRE_ROL"        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "IDENTIFICADOR_ROL" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID_ROL") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;
  
  --SECUENCIAS
  CREATE SEQUENCE SEC_USUARIOS INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1 ORDER;

