package co.urbaNatt.constans;

public class CamposTablaConstans {
	
	//usuarios
	public static final String ID_USUARIO = "ID_USUARIO";
	public static final String NOMBRE_USUARIO = "NOMBRE_USUARIO";
	public static final String CONTRASENIA_USUARIO = "CONTRASENIA_USUARIO";
	public static final String FECHA_CREACION = "FECHA_CREACION";
	public static final String CANTIDAD_INTENTOS_INGRESO = "CANTIDAD_INTENTOS_INGRESO";
	public static final String ESTADO = "ESTADO";
	public static final String NOMBRE_COMPLETO = "NOMBRE_COMPLETO";
	public static final String ID_ROL_USUARIO = "ID_ROL_USUARIO";
	public static final String NOTA = "NOTA";
	public static final String COMA = ",";
	
	public static final String CAMPOS_USUARIO = ID_USUARIO + COMA +NOMBRE_USUARIO + COMA + CONTRASENIA_USUARIO + COMA + FECHA_CREACION + COMA + CANTIDAD_INTENTOS_INGRESO + COMA
			+ ESTADO + COMA + NOMBRE_COMPLETO + COMA + ID_ROL_USUARIO +COMA+NOTA;
	
	public static final String CAMPOS_CLIENTE = "ID_CLIENTE, TIPOID, NUMID, NOMBRECOMPLETO,FIJO, CELULAR, CORREO, DIRECCION, DEPARTAMENTO, CIUDAD, ESTADO, FECHACREACION";
	
	public static final String CAMPOS_SUCURSAL = "ID_SUCURSAL,NOMBRESUCURSAL,TIPO,DIRECCION,DEPARTAMENTO, CIUDAD, ID_CLIENTE";
	
	public static final String CAMPOS_PRODUCTO = "ID_PRODUCTO, NOMBRE, TIPO,UNIDAD,DESCRIPCION,CANTIDAD, PESO, VALOR";
	public static final String CAMPOS_FACTURA = "ID_FACTURA,NUMERO_FACTURA,ID_CLIENTE, FECHA_CREACION, FECHA_FACTURA, VALOR_DEUDA, VALOR_PAGADO, ESTADO, VALOR_FACTURA, DESCRIPCION, TIPO, ID_SUCURSAL,FECHA_PAGO_TOTAL";
	public static final String CAMPOS_FACTURA_PRODUCTO = "ID_FACTURA_PRODUCTO, ID_FACTURA, ID_PRODUCTO, FECHA_CREACION, CANTIDAD, NOMBRE_PRODUCTO,TIPO,VALOR_UNITARIO";
	public static final String CAMPOS_DETALLE_FACTURA = "ID_DETALLE,ID_FACTURA, FECHA_CREACION, VALOR_PAGADO, ESTADO, NUMERO_RECIBO, NUMERO_FACTURA";
	

}
